version: '3.8'

services:
  app:
    image: ankit/sprintapp:1.0.0
    ports:
      - 8085:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/localspringboot
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: localspringboot
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
